#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CH-FPK-06 Flat-Pack Container Homes - build verifier.

    python verify_chfpk06.py <preview-url | rendered-html-file>

Prints RESULT: PASS or RESULT: FAIL. Do not edit this file to make a build pass.
"""
import sys, os, re, json, io, html, unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
COPY = os.path.join(HERE, "CH-FPK-06-flat-pack-container-homes-copy-v1.json")
AMAP = os.path.join(HERE, "CH-FPK-06-flat-pack-container-homes-asset-map-v1.json")

TOKENS  = ["#1a3c2e", "#2d7a3f", "#f0f7f2"]
TAB_PAIRS = [("Description", "Info"), ("Specifications", "Specs"),
             ("Shipping", "Ship"), ("Reviews", "Reviews")]
EMPTY_SLOT_PHRASES = ["available on request", "coming soon", "contact us for details",
                      "to be confirmed", "tbd", "lorem ipsum"]
FORBIDDEN_FACTS = ["working days", "7 to 21", "5 year structural", "5-year structural"]
# figures we have no source for; a bare disclaimer naming the topic is fine, a number is not
FORBIDDEN_FIGURES = [
    (r"service life[^.]{0,60}?\d", "a service-life figure"),
    (r"\d+\s*(?:to\s*\d+\s*)?(?:reassembl|relocation)", "a reassembly or relocation count"),
    (r"\d+\s*(?:crates?|kg\b|cbm\b|m3\b)", "a crate count, pack weight or pack volume"),
    (r"(?:fire|thermal|acoustic)\s+rating[^.]{0,40}?\d", "a fire, thermal or acoustic rating"),
]
RETIRED = ["prebuilt-container-homes", "prefabricated-container-home",
           "prefabricated-container-house", "affordable-container-homes",
           "inexpensive-container-homes", "modern-container-home",
           "cargo-container-house", "storage-container-house"]

fails, checks = [], [0]

def ok(cond, msg):
    checks[0] += 1
    if not cond:
        fails.append(msg)
    return cond

def load_html(arg):
    if os.path.exists(arg):
        return io.open(arg, encoding="utf-8", errors="replace").read()
    try:
        from urllib.request import urlopen, Request
        req = Request(arg, headers={"User-Agent": "SAMAN-verifier/1.0"})
        return urlopen(req, timeout=60).read().decode("utf-8", "replace")
    except Exception as e:
        print("could not read %s: %s" % (arg, e))
        sys.exit(2)

def text_of(h):
    h = re.sub(r"(?is)<script.*?</script>", " ", h)
    h = re.sub(r"(?is)<style.*?</style>", " ", h)
    h = re.sub(r"(?s)<[^>]+>", " ", h)
    return re.sub(r"\s+", " ", html.unescape(h)).strip()

def norm(t):
    t = unicodedata.normalize("NFKC", t)
    for a, b in [("’", "'"), ("‘", "'"), ("“", '"'), ("”", '"'),
                 ("′", "'"), ("″", '"'), ("–", "-"), (" ", " ")]:
        t = t.replace(a, b)
    return re.sub(r"\s+", " ", t).strip()

def present(hay, needle, label):
    n = norm(re.sub(r"(?s)<[^>]+>", "", needle))
    ok(n and n in hay, "missing verbatim string: %s :: %s" % (label, n[:90]))

def main():
    if len(sys.argv) < 2:
        print("usage: verify_chfpk06.py <preview-url | rendered-html-file>"); sys.exit(2)
    raw = load_html(sys.argv[1])
    body = text_of(raw)
    hay  = norm(body)
    c = json.load(io.open(COPY, encoding="utf-8"))
    am = json.load(io.open(AMAP, encoding="utf-8"))

    # ---------------------------------------------------------------- 1 counts
    mt, md, h1 = c["meta"]["title"], c["meta"]["description"], c["h1"]
    ok(55 <= len(mt) <= 60, "meta title %d chars, need 55-60" % len(mt))
    ok(150 <= len(md) <= 160, "meta description %d chars, need 150-160" % len(md))
    ok(50 <= len(h1) <= 60, "H1 %d chars, need 50-60" % len(h1))
    ok(mt.count("SAMAN") == 1, "meta title must contain SAMAN exactly once")
    ok(len(re.findall(r"(?is)<h1[\s>]", raw)) == 1,
       "page must have exactly one H1, found %d" % len(re.findall(r"(?is)<h1[\s>]", raw)))
    hero = c["hero"]["short_description"]
    ok(700 <= len(hero) <= 800, "hero %d chars, need 700-800" % len(hero))

    s2 = c["section2"]
    ok(55 <= len(s2["h2"]) <= 70, "section 2 H2 %d chars, need 55-70" % len(s2["h2"]))
    p1 = s2["paragraphs"][0]
    p2 = "".join(x if isinstance(x, str) else x["link_text"] for x in s2["paragraphs"][1]["parts"])
    ok(800 <= len(p1) + len(p2) <= 900,
       "section 2 paragraphs %d chars combined, need 800-900" % (len(p1) + len(p2)))
    ok(len(s2["paragraphs"]) == 2, "section 2 must have exactly two paragraphs")
    sc = s2["split_card"]
    ok(35 <= len(sc["h3"]) <= 65, "split card H3 %d chars, need 35-65" % len(sc["h3"]))
    for i, p in enumerate(sc["paragraphs"]):
        ok(150 <= len(p) <= 220, "split card paragraph %d is %d chars, need 150-220" % (i+1, len(p)))

    s3 = c["section3"]
    ok(50 <= len(s3["h2"]) <= 60, "section 3 H2 %d chars, need 50-60" % len(s3["h2"]))
    ok(100 <= len(s3["intro"]) <= 140, "section 3 intro %d chars, need 100-140" % len(s3["intro"]))
    ok(len(s3["sizes"]) == 6, "section 3 must carry six sizes")
    for s in s3["sizes"]:
        ok(50 <= len(s["h3"]) <= 62, "%s H3 %d chars, need 50-62" % (s["code"], len(s["h3"])))
        ok(400 <= len(s["paragraph"]) <= 500,
           "%s paragraph %d chars, need 400-500" % (s["code"], len(s["paragraph"])))
        ok(5 <= len(s["bullets"]) <= 6, "%s has %d bullets, need 5-6" % (s["code"], len(s["bullets"])))
    ok(len(c["you_may_also_like"]["intro"]) < 90, "you-may-also-like intro must be under 90 chars")

    # ---------------------------------------------- 2 every string verbatim on page
    present(hay, hero, "hero")
    for k in ("h2", "cta"): present(hay, s2[k], "section2." + k)
    present(hay, p1, "section2.p1")
    present(hay, sc["h3"], "splitcard.h3")
    for p in sc["paragraphs"]: present(hay, p, "splitcard.p")
    present(hay, sc["cta"], "splitcard.cta")
    present(hay, s3["h2"], "section3.h2"); present(hay, s3["intro"], "section3.intro")
    for s in s3["sizes"]:
        present(hay, s["h3"], s["code"] + ".h3")
        present(hay, s["paragraph"], s["code"] + ".para")
        for b in s["bullets"]: present(hay, b, s["code"] + ".bullet")
    for cells in c["hero"]["feature_cells"].values():
        for cell in cells: present(hay, cell, "feature_cell")
    d = c["tabs"]["description"]
    for sec in d["sections"]:
        present(hay, sec["h2"], "desc.h2")
        for b in sec["blocks"]:
            if b["type"] == "p": present(hay, b["html"], "desc.p")
            elif b["type"] == "bullets":
                for it in b["items"]: present(hay, it, "desc.bullet")
            elif b["type"] == "table":
                for row in b["rows"]:
                    for cell in row:
                        if cell: present(hay, cell, "desc.table")
    for f in d["faq"]:
        present(hay, f["q"], "faq.q"); present(hay, f["a"], "faq.a")
    sp = c["tabs"]["specifications"]
    for p in sp["narrative"]: present(hay, p, "spec.narrative")
    for g in ("group_a", "group_b", "group_c", "group_d", "group_e"):
        for row in sp[g]["rows"]:
            for cell in row:
                if cell and len(cell) > 3: present(hay, cell, g)

    # ------------------------------------------------------------- 3 structure
    ok(6 <= len(d["faq"]) <= 8, "need 6-8 FAQs, found %d" % len(d["faq"]))
    for f in d["faq"]:
        ok(100 <= len(f["a"]) <= 300,
           "FAQ answer %d chars, need 100-300: %s" % (len(f["a"]), f["q"][:50]))
    blocks = [b["type"] for sec in d["sections"] for b in sec["blocks"]]
    ok(blocks.count("bullets") == 1,
       "description tab must have exactly one bullet block, found %d" % blocks.count("bullets"))
    ok(blocks.count("table") <= 1,
       "description tab must have zero or one table, found %d" % blocks.count("table"))
    words = 0
    for sec in d["sections"]:
        words += len(sec["h2"].split())
        for b in sec["blocks"]:
            if b["type"] == "p":
                words += len(re.sub(r"<[^>]+>", " ", b["html"]).split())
            elif b["type"] == "bullets":
                words += sum(len(i.split()) for i in b["items"])
            elif b["type"] == "table":
                words += sum(len(" ".join(r).split()) for r in b["rows"])
    words += len(d["faq_h2"].split()) + sum(len((f["q"] + " " + f["a"]).split()) for f in d["faq"])
    ok(2000 <= words <= 3000, "description tab %d visible words, need 2000-3000" % words)
    for h2 in [s["h2"] for s in d["sections"]] + [d["faq_h2"]]:
        ok(40 <= len(h2) <= 60, "description H2 %d chars, need 40-60: %s" % (len(h2), h2[:50]))
    ok(len(sp["narrative"]) in (2, 3), "specifications tab needs 2 or 3 narrative paragraphs")

    # ------------------------------------------------------------ 4 tabs, tokens
    flat = re.sub(r"\s+", "", body)
    for lng, shrt in TAB_PAIRS:
        ok((lng + shrt) in flat or (lng == shrt and lng in flat),
           "tab label pair missing or wrong; a flattened scrape must read %s%s" % (lng, shrt))
    ok("DescriptionDescription" not in flat,
       "the small-screen tab label was set to the long word; it must read DescriptionInfo")
    ok(len(re.findall(r"(?i)\bTab\b", "")) == 0, "")
    low = raw.lower()
    for ph in EMPTY_SLOT_PHRASES:
        ok(ph not in body.lower(), "empty-slot fallback phrase reached the page: %s" % ph)
    nb = re.sub(r"[\u2013\u2014-]", " to ", body.lower())
    nb = re.sub(r"\s+", " ", nb)
    for ph in FORBIDDEN_FACTS:
        ok(ph.replace("-", " to ") not in nb and ph not in body.lower(),
           "unsourced fact published on the page: %s" % ph)
    for pat, what in FORBIDDEN_FIGURES:
        ok(not re.search(pat, nb), "unsourced figure published on the page: %s" % what)
    for t in TOKENS: ok(t in low, "design token missing from the page: %s" % t)

    # ------------------------------------------------------------- 5 prices
    for s in c["sizes"]:
        ok(s["price_ex_gst"] in body, "ex-GST price missing for %s: %s" % (s["code"], s["price_ex_gst"]))
        ok(s["price_incl_gst"] in body, "incl-GST price missing for %s" % s["code"])
        ok(s["display"].replace(" ft", "") in body.replace(" ft", "") or s["tab_label"] in body,
           "size label missing: %s" % s["display"])
    ok(len(c["sizes"]) == 6, "the size ladder must carry exactly six sizes")

    # ------------------------------------------------------------ 6 structured data
    blobs = re.findall(r'(?is)<script[^>]+application/ld\+json[^>]*>(.*?)</script>', raw)
    types, faq_answers = set(), []
    for b in blobs:
        try: data = json.loads(b)
        except Exception: continue
        for node in (data if isinstance(data, list) else [data]):
            for n in (node.get("@graph", [node]) if isinstance(node, dict) else []):
                t = n.get("@type")
                for tt in (t if isinstance(t, list) else [t]):
                    if tt: types.add(tt)
                if n.get("@type") == "Product" and isinstance(n.get("offers"), dict):
                    types.add(n["offers"].get("@type", ""))
                if n.get("@type") == "FAQPage":
                    for q in n.get("mainEntity", []):
                        faq_answers.append(norm(text_of(q.get("acceptedAnswer", {}).get("text", ""))))
    for t in ("ItemPage", "Product", "AggregateOffer", "BreadcrumbList", "FAQPage"):
        ok(t in types, "structured data type missing: %s" % t)
    extra = types - {"ItemPage", "Product", "AggregateOffer", "BreadcrumbList", "FAQPage",
                     "ListItem", "Offer", "Question", "Answer", "BreadcrumbList", "WebPage", ""}
    ok(not extra, "unexpected structured data types: %s" % ", ".join(sorted(extra)))
    ok("aggregateRating" not in raw, "aggregateRating must not be emitted: there are no verified reviews")
    for f in d["faq"]:
        ok(norm(f["a"]) in faq_answers,
           "FAQ answer not byte-identical in FAQPage schema: %s" % f["q"][:50])

    # ------------------------------------------------------------- 7 assets
    alts, imgs = [], 0
    for slug, sz in am["sizes"].items():
        ok(len(sz["gallery"]) == 6, "size %s must have six gallery slides" % slug)
        ext = [g for g in sz["gallery"] if "interior" not in g["slot"] + g["public_path"]]
        ok(len([g for g in sz["gallery"] if "-interior" in g["public_path"]]) == 2,
           "size %s must run four exteriors then two interiors" % slug)
        for i, g in enumerate(sz["gallery"]):
            ok(os.path.exists(g["file"]), "gallery file missing on disk: %s" % g["file"])
            ok(g["format"] == "webp" and g["width"] == g["height"],
               "gallery slide must be square WebP: %s" % g["slot"])
            ok(g["kb"] is not None and 80 <= g["kb"] <= 120,
               "gallery slide outside the 80-120 KB band: %s at %s KB" % (g["slot"], g["kb"]))
            ok(bool(g["alt"]) and len(g["alt"]) > 25, "gallery alt text too short: %s" % g["slot"])
            ok(g["public_path"] in raw, "gallery image not referenced: %s" % g["public_path"])
            ok(g["loading"] == ("eager" if i == 0 else "lazy"),
               "wrong loading attribute on %s/%s" % (slug, g["slot"]))
            alts.append(g["alt"]); imgs += 1
        b = sz["section3_left_panel"]
        ok(os.path.exists(b["file"]), "section 3 left panel missing on disk: %s" % b["file"])
        ok(b["aspect"] == "4:3", "the section 3 left panel must be 4:3, measured on the live lock")
        ok(abs(b["width"] * 3 - b["height"] * 4) <= 2,
           "section 3 left panel is not exactly 4:3: %sx%s" % (b["width"], b["height"]))
        ok(b["never_crop"] is True, "the section 3 board must be marked never_crop")
        ok(80 <= b["kb"] <= 120, "section 3 panel outside the band: %s KB" % b["kb"])
        ok(b["public_path"] in raw, "section 3 left panel not referenced: %s" % b["public_path"])
        alts.append(b["alt"]); imgs += 1
    sh = am["shared"]["section2_split_card"]
    ok(sh["aspect"] == "16:9", "section 2 split card must be 16:9")
    ok(abs(sh["width"] * 9 - sh["height"] * 16) <= 2, "section 2 split card is not exactly 16:9")
    ok(80 <= sh["kb"] <= 120, "section 2 split card outside the band: %s KB" % sh["kb"])
    ok(sh["public_path"] in raw, "section 2 split card not referenced on the page")
    alts.append(sh["alt"]); imgs += 1
    ok(am["shared"]["media_band"] is None, "there must be no media band on this page")
    for gone in ("m1-flat-pack", "m2-flat-pack", "m3-flat-pack"):
        ok(gone not in raw, "withdrawn media-band image referenced on the page: %s" % gone)
    di = am["shared"]["description_tab_images"]
    ok(len(di) == 6, "the Description tab must carry six long-description images, found %d" % len(di))
    for d_ in di:
        ok(os.path.exists(d_["file"]), "description image missing on disk: %s" % d_["file"])
        ok(d_["aspect"] == "16:9" and abs(d_["width"] * 9 - d_["height"] * 16) <= 2,
           "description image is not exactly 16:9: %s" % d_["slot"])
        ok(80 <= d_["kb"] <= 120, "description image outside the band: %s KB" % d_["kb"])
        ok(d_["public_path"] in raw, "description image not referenced: %s" % d_["public_path"])
        alts.append(d_["alt"]); imgs += 1
    sd = am["shared"]["spec_diagrams"]
    ok(len(sd) == 6, "all six kit boards must sit in the Specifications tab, found %d" % len(sd))
    for d_ in sd:
        ok(os.path.exists(d_["file"]), "specifications board missing on disk: %s" % d_["file"])
        ok(d_["never_crop"] is True, "specifications boards must be marked never_crop")
        ok(80 <= d_["kb"] <= 120, "specifications board outside the band: %s KB" % d_["kb"])
        ok(d_["public_path"] in raw, "specifications board not referenced: %s" % d_["public_path"])
        alts.append(d_["alt"]); imgs += 1
    ok(len(set(alts)) == len(alts), "duplicate alt text across image slots")
    ok(all(a.strip() for a in alts), "an empty alt attribute is present")
    ok(".png" not in raw.lower().replace("png_", ""), "a source PNG has reached the page; PNGs must not be served")
    ep = c.get("explore_panel", {})
    ok(ep.get("resolve_at_build_time") is True, "the Explore panel must resolve at build time")
    hrefs = [x["href"] for x in ep.get("candidates", [])]
    ok(len(hrefs) == len(set(hrefs)), "duplicate tile in the Explore panel candidate list")
    ok(all("/product/container-houses" in h for h in hrefs),
       "a cross-cluster tile is present in the Explore panel candidate list")
    ok(c["meta"]["canonical"] not in [h for h in hrefs],
       "the current page must be excluded from its own Explore panel")

    # ------------------------------------------------------------ 8 links, dashes
    for r in RETIRED:
        ok(r not in raw, "retired URL is linked on the page: %s" % r)
    ok(c["section2"]["paragraphs"][1]["parts"][1]["href"] in raw,
       "section 2 contextual internal link is missing")
    for item in c["you_may_also_like"]["items"]:
        ok(item["href"] in raw, "you-may-also-like link missing: %s" % item["href"])
    ok("—" not in body, "U+2014 em dash found in body copy; it is not permitted")
    ok(c["meta"]["canonical"] in raw, "self-referencing canonical missing")
    ok("No verified reviews yet." in body, "the reviews empty state must render")

    print()
    print("checks run: %d" % checks[0])
    if fails:
        print("failures: %d" % len(fails))
        for f in fails: print("  - " + f)
        print(); print("RESULT: FAIL"); sys.exit(1)
    print("failures: 0"); print(); print("RESULT: PASS")

if __name__ == "__main__":
    main()
